### ISSUE TITLE
Commentable models discovery issues

### ISSUE THREAD

**Issue by topclaudy** [Lakshan-Madushanka/laravel-comments-admin-panel#5]
Can we have a config where we can specify the Commentable models instead of parsing the app/Models? First of all, the current approach is bogus and ignore some models when there are nested namespaces. The other issue is that models extending a Commentable model will be treated as Commentable.

Here is what I did to make it works in my situation:

1) I added a `models` key in the config:
![Screenshot 2024-08-05 at 10 07 54](https://github.com/user-attachments/assets/0dc8249c-136a-4cba-9985-7336da194ead)

2) then use it when loading the models (instead of recursively scanning app/Models)
![Screenshot 2024-08-05 at 10 08 32](https://github.com/user-attachments/assets/a5d8a609-f5c6-4566-b09d-e67df98d60dc)

**Comment by Lakshan-Madushanka** [comment]
@topclaudy Are you using new newest version? with the release [v.1.0.2](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel/releases/tag/1.0.2) this should be resolved.

![Screenshot 2024-08-05 200043](https://github.com/user-attachments/assets/14247c35-2260-41dd-9b10-2d5690df3017)

**Comment by topclaudy** [comment]
Yes. I'm using the last version. The issue I reported is fixed but it ignores some models. And there is the issue of subclasses of Commentable models being treated as Commentable.

**Comment by Lakshan-Madushanka** [comment]
@topclaudy Can you describe what kind of models it ignores.

I didn't get  what you mean exactly below. If a model implement CommentableContract must be a commentable model. Isn't that the only reason for implementing it or perhaps you don't need admin panel to track some commentable modes ?

> And there is the issue of subclasses of Commentable models being treated as Commentable.

**Comment by topclaudy** [comment]
I have a base model `App\Models\Quotes\Quote.php`. It implements `CommentableContract`. I have many (about 5) subclasses of the model `App\Models\Quotes\Quote.php` (linked to the same table in DB) that also appear on the dashboard. I only want `App\Models\Quotes\Quote.php` to appear in the dashboard (not its subclasses). 

If you want to keep the way it is, can we have a config to filter out some models?

Regarding the model discovery bug, the code can't find the model `Quote` (which implements `CommentableContract` ) for the following directory structure: 

![Screenshot 2024-08-05 at 12 13 22](https://github.com/user-attachments/assets/2a23efe6-3130-4eda-a5ec-cdeab2316d2b)

It looks like it only processes the subfolder `Archive` and skip the remaining files/folders.

Hope this clarifies the issues.

**Comment by Lakshan-Madushanka** [comment]
Clear. It's very delicate situation. will fix soon.

**Comment by Lakshan-Madushanka** [comment]
@topclaudy Sub classes issue is actually because of the way inheritance behave so I added ability to explicitly define commentable models but I tested second issue using similar folder structure as yours; It works fine.

However please refer to the [v.1.1.0](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel/releases/tag/1.1.0) and notify if issues are still exists

**Comment by topclaudy** [comment]
Hi @Lakshan-Madushanka. Thanks for the update. The new setting `commentable_models` works fine. However, the issue for models discovery persists.

When I use the setting `commentable_models`, I get:

![Screenshot 2024-08-06 at 06 47 30](https://github.com/user-attachments/assets/ddaa7081-40af-45c2-8921-3688ebb33a57)
_(there is a slight UI issue in the sidebar when namespace is long)_

Without the setting (when the `commentable_models` array is empty), I get:

![Screenshot 2024-08-06 at 06 49 31](https://github.com/user-attachments/assets/57f8421e-80d8-4a11-b699-28d06a922ca0)

Anyway, I think I'm gonna use the `commentable_models` setting from now on.

**Comment by Lakshan-Madushanka** [comment]
@topclaudy UI issue is fixed. Make sure to remove previous assets and re-publish them. I can look into the model discovery issue if you can provide more details.

**Comment by topclaudy** [comment]
@Lakshan-Madushanka The UI issue is fixed. Thanks.

For the model discovery, here is the code that works in my situation:

```
private function loadModels(string $path, array &$models = []): array
    {
        foreach(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path)) as $file){
                if ($file->isDir()) {
                    continue;
                }

                if (($ext = $file->getExtension()) === 'php') {
                    $basePath = str_replace(app_path(), '', $file->getPathName());
                    $namespace = str_replace('.' . $ext, '', 'App' . $basePath);
                    $namespace = str_replace(DIRECTORY_SEPARATOR, '\\', $namespace);

                    if (is_subclass_of($namespace, Model::class) && is_subclass_of($namespace, CommentableContract::class)) {
                        $key = str($namespace)
                            ->afterLast('App' . DIRECTORY_SEPARATOR . 'Models' . DIRECTORY_SEPARATOR)
                            ->studly()
                            ->value();

                        $models[$key]['count'] = 0;
                        $models[$key]['instance'] = new $namespace();
                    }
                }
        }

        return $models;
    }
```

It doesn't explicitly use recursion and involves `RecursiveDirectoryIterator`. Keep in mind that I'm using a Mac.

As I mentioned before, I'm happy with the `commentable_models` setting because I don't want subclasses to get listed. But you can update the code to prevent future bug report.

**Comment by Lakshan-Madushanka** [comment]
Fix with [v1.1.2](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel/releases/tag/1.1.2) 

Mainly, it was because I had used `DIRECTORY_SEPARATOR` for the namespace separator as well, which works for Windows as it uses `/` in both cases, but it may not work in other OS.

@topclaudy Thanks for the support.

**Comment by topclaudy** [comment]
@Lakshan-Madushanka [v1.1.2](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel/releases/tag/1.1.2) works. Thanks!
